name: plural_app
description: An open-source mutual aid application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  timeline_tile: ^2.0.0
  intl: ^0.20.2
  pocketbase: ^0.23.0
  get_it: ^8.0.0
  go_router: ^16.0.0
  validators: ^3.0.0
  url_launcher: ^6.3.1
  url_launcher_platform_interface: ^2.3.2
  plugin_platform_interface: ^2.1.8
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  test: ^1.25.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/common/